name: blackswan
channels:
- birdhouse
- conda-forge
- defaults

# the r hell ...
- r
- bioconda  # for r-mclust

# ocgis
# - nesii/label/ocgis-next
# - nesii/label/dev-esmf

dependencies:
###### base ##########
- pywps=4.2
- jinja2
- click
- psutil
######################
- python=3
- numpy
#- ocgis
- gdal=2.4
# We use ocgis version of netcdf4
# - netcdf4
- scipy
- statsmodels
- pandas
- pypdf2
#####################
- matplotlib
- cartopy
#####################
- cdo #=1.9.4
- python-cdo
- xarray
###### analogue#####
#- castf90=0.1.5
####################

####### R ##########
- cairo
- r
- r-ggplot2
- r-plotly
- pandoc # for html
###################

- pip:
  - -e git+https://github.com/NCPP/ocgis#egg=owslib
