name: blackswan
channels:
# ocgis
- nesii/label/ocgis-next
- nesii/label/dev-esmf
- birdhouse
- conda-forge
- defaults
# the r hell ...
- r
- bioconda  # for r-mclust
dependencies:
- python=2.7
- ipython
- gcc
#- glib=2.48.0
- pyopenssl
- cryptography
- psutil
- cffi
- setuptools=27.2.0
- icu=58.1
- libxslt
- json-c=0.12.1 # See issue #251
- pypdf2
################
# tests
- pytest
- nose
# pep8
- flake8
- pycodestyle
################
# docs
- sphinx
- sphinx_rtd_theme
- doc8
################
# wps
- nginx
- supervisor=3.3.1
- gunicorn=19
- gevent
- pywps=4.0.0
- mako
- genshi
################
# misc
#- pywget
- pyyaml=3.12
- jinja2=2
################
# numeric
- numpy
- scipy=1.1.0=py27_blas_openblas_200 # pinned due to issue #248
- pandas #=0.18.1
- statsmodels #=0.6.1
- scikit-learn #=0.17.1
################
# visualisation
- matplotlib=2.0.2=py27_2 #2.0.0=np112py27_2
- functools32=3.2.3.2=py27_0 # badly pinned matplotlib dependency
- cartopy
- iris
- reportlab
# visualisation EO-data
# - python-snappy   # =0.5.1=py27_2 # conda-forge
# - snappy        # conda-forge
################
## cdo ocgis
- cdo #=1.9.0=0
#- hdf5=1.8.18=1
- libnetcdf=4.4.1.1
- python-ecmwf_grib=1.23.1
- python-cdo=1.3.4
- ocgis-next
- esmf
- esmpy
# - icclim
- proj4 #=4.9.3
- geos #=3.5.1=1
- jpeg=9b
- gdal=2.1.3
# ################
# # analogue
- castf90=0.1.5
# ################
# # r
- cairo # for X11 independend plot support
- r #=3.2  # 3.3 conflicts with icu=56
- rpy2 #=2.7.0
- r-mclust #=5.1 subsuituted by cluster
- r-ncdf4=1.15=1
- r-pracma
- r-future.apply
- r-fields #=8.4 conflicts with r3.3.1 needs 3.2
- r-gridextra #=2.0.0
- r-ggplot2
- r-plotly # interactive plots
- r-extremes
- harfbuzz
- pandoc # for html output for ggplot
# #- r-cairo#=1.5_9 build in r-base
################
# esgf
- esgf-pyclient
# satetlite
- rasterio
- retrying
- pip:
  - pygbif==0.2.0 #0.1.4
  - sphinx-autoapi==0.5.0
#  - cdo==1.3.0
  # - sentinelsat
  - --editable=git+https://github.com/huard/sphinx-autodoc-pywps.git#egg=sphinx_autodoc_pywps
#  - planet
#  - rasterio
#  - retrying
